apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-txnt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-txnt
    app.kubernetes.io/part-of: tkwch-fix-0075-0006-app
  name: devfile-sample-txnt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-txnt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-txnt
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0006-tenant/tkwch-fix-0075-0006-app/devfile-sample-txnt@sha256:766b2ba923cb2ee4706497225041280ea300398d23ad76335f2a8adb23d9c6de
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
